const linkIconOption =[
      {
        key:1,
        value:'去配置页面'
      },{
        key:2,
        value:'去H5页面'
      },{
        key:3,
        value:'去商品详情页'
      },{
        key:4,
        value:'去上新尖货页'
      },{
        key:5,
        value:'去热卖爆款页'
      },{
        key:6,
        value:'去保税专区页'
      },{
        key:7,
        value:'去品牌馆页'
      },{
        key:9,
        value:'去全部商品分类页'
      },{
        key:8,
        value:'去商品分类'
      },{
        key:10,
        value:'去促销活动页'
      }]
const linkOption =[
  {
        key:1,
        value:'去配置页面'
      },{
        key:2,
        value:'去H5页面'
      },{
        key:3,
        value:'去商品详情页'
      },{
        key:4,
        value:'去上新尖货页'
      },{
        key:5,
        value:'去热卖爆款页'
      },{
        key:6,
        value:'去保税专区页'
      },{
        key:7,
        value:'去品牌馆页'
      },{
        key:8,
        value:'去商品分类'
      },{
        key:10,
        value:'去促销活动页'
      }]
const linkOptionTwo =[{
        key:1,
        value:'去配置页面'
      },{
        key:2,
        value:'去H5页面'
      },{
        key:4,
        value:'去上新尖货页'
      },{
        key:5,
        value:'去热卖爆款页'
      },{
        key:6,
        value:'去保税专区页'
      },{
        key:7,
        value:'去品牌馆页'
      },{
        key:8,
        value:'去商品分类'
      },{
        key:10,
        value:'去促销活动页'
      }]

export {
  linkIconOption,
  linkOption,
  linkOptionTwo
}
