const SiderBarData = [
    {
      "urResourceId": 200000,
      "name": "订单中心",
      "code": "200000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 1,
      "children": [
        {
          "urResourceId": 201000,
          "name": "门店订单",
          "code": "201000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 1,
          "children": [
            {
              "urResourceId": 201100,
              "name": "订单信息",
              "code": "201100",
              "url": "qerp.web.sp.order.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 201200,
              "name": "新增订单",
              "code": "201200",
              "url": "qerp.web.sp.order.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 201300,
              "name": "取消订单",
              "code": "201300",
              "url": "qerp.web.sp.order.cancel",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 201400,
              "name": "数据导出",
              "code": "201400",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 201500,
              "name": "新增赠品订单",
              "code": "201500",
              "url": "qerp.web.sp.order.gift.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 203000,
          "name": "门店退单",
          "code": "203000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 2,
          "children": [
            {
              "urResourceId": 203100,
              "name": "订单信息",
              "code": "203100",
              "url": "qerp.web.ws.asn.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 203200,
              "name": "新增退货单",
              "code": "203200",
              "url": "qerp.web.ws.asn.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 203300,
              "name": "导出数据",
              "code": "203300",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 203400,
              "name": "强制完成",
              "code": "203400",
              "url": "qerp.web.ws.asn.finish",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 202000,
          "name": "采购订单",
          "code": "202000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 3,
          "children": [
            {
              "urResourceId": 202100,
              "name": "订单信息",
              "code": "202100",
              "url": "qerp.web.ws.asn.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 202200,
              "name": "增改采购单",
              "code": "202200",
              "url": "qerp.web.ws.asn.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 202300,
              "name": "强制完成",
              "code": "202300",
              "url": "qerp.web.ws.asn.finish",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 202600,
              "name": "打印采购单",
              "code": "202600",
              "url": "qerp.web.sp.order.print",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 202700,
              "name": "导出数据",
              "code": "202700",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 202800,
              "name": "发票管理",
              "code": "202800",
              "url": "qerp.web.ws.invoice.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 204000,
          "name": "采退订单",
          "code": "204000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 4,
          "children": [
            {
              "urResourceId": 204100,
              "name": "订单信息",
              "code": "204100",
              "url": "qerp.web.sp.ctorder.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 204200,
              "name": "新增采退单",
              "code": "204200",
              "url": "qerp.web.sp.ctorder.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 204300,
              "name": "导出数据",
              "code": "204300",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 207000,
          "name": "用户订单",
          "code": "207000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 5,
          "children": [
            {
              "urResourceId": 207100,
              "name": "订单信息",
              "code": "207100",
              "url": "qerp.web.user.st.order.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 207200,
              "name": "导出数据",
              "code": "207200",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 208000,
          "name": "用户退单",
          "code": "208000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 6,
          "children": [
            {
              "urResourceId": 208100,
              "name": "全部退单",
              "code": "208100",
              "url": "",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 208300,
                  "name": "订单信息",
                  "code": "208300",
                  "url": "qerp.web.pd.order.return.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 208500,
                  "name": "确认收货",
                  "code": "208500",
                  "url": "qerp.web.pd.order.return.confirm",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 208600,
                  "name": "强制取消",
                  "code": "208600",
                  "url": "qerp.web.pd.order.return.cancel",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            },
            {
              "urResourceId": 208200,
              "name": "待运营审核",
              "code": "208200",
              "url": "",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 208700,
                  "name": "订单信息",
                  "code": "208700",
                  "url": "qerp.web.pd.order.return.audited.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 208800,
                  "name": "审核",
                  "code": "208800",
                  "url": "qerp.web.pd.order.return.audited",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            }
          ]
        },
        {
          "urResourceId": 801000,
          "name": "保税仓订单",
          "code": "801000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 7,
          "children": [
            {
              "urResourceId": 801100,
              "name": "订单信息",
              "code": "801100",
              "url": "qerp.web.ec.od.userOrder.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 801200,
              "name": "重新推送",
              "code": "801200",
              "url": "qerp.web.ec.od.repush",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 801500,
              "name": "导出数据",
              "code": "801500",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 801600,
              "name": "重新匹配商品",
              "code": "801600",
              "url": "qerp.web.ec.od.userOrder.rematch",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 801800,
              "name": "修改订单",
              "code": "801800",
              "url": "qerp.web.ec.pd.userOrder.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 804000,
          "name": "待审核订单",
          "code": "804000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 8,
          "children": [
            {
              "urResourceId": 804100,
              "name": "订单信息",
              "code": "804100",
              "url": "qerp.web.ec.od.auditOrder.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 804200,
              "name": "订单拆分",
              "code": "804200",
              "url": "qerp.web.ec.od.auditOrder.dismantle.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 804300,
              "name": "订单合并",
              "code": "804300",
              "url": "qerp.web.ec.od.auditOrder.merge.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 804400,
              "name": "星标",
              "code": "804400",
              "url": "qerp.web.ec.od.auditOrder.icon",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 804500,
              "name": "修改价格",
              "code": "804500",
              "url": "qerp.web.ec.od.auditOrder.price.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 804600,
              "name": "审核通过",
              "code": "804600",
              "url": "qerp.web.ec.od.auditOrder.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 206000,
          "name": "调拨订单",
          "code": "206000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 9,
          "children": [
            {
              "urResourceId": 206100,
              "name": "订单信息",
              "code": "206100",
              "url": "qerp.web.sp.exchange.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 206200,
              "name": "新增调拨单",
              "code": "206200",
              "url": "qerp.web.sp.exchange.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 206300,
              "name": "导出数据",
              "code": "206300",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 206400,
              "name": "强制完成",
              "code": "206400",
              "url": "qerp.web.ws.asn.finish",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 205000,
          "name": "POS订单",
          "code": "205000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 10,
          "children": [
            {
              "urResourceId": 205100,
              "name": "订单信息",
              "code": "205100",
              "url": "qerp.web.qpos.st.order.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 205200,
              "name": "导出数据",
              "code": "205200",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        }
      ]
    },
    {
      "urResourceId": 300000,
      "name": "商品中心",
      "code": "300000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 2,
      "children": [
        {
          "urResourceId": 301000,
          "name": "基础商品",
          "code": "301000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 1,
          "children": [
            {
              "urResourceId": 301100,
              "name": "商品信息",
              "code": "301100",
              "url": "qerp.web.basepd.spu.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 301200,
              "name": "增改线上商品",
              "code": "301200",
              "url": "qerp.web.pd.spu.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 301300,
              "name": "增改线下商品",
              "code": "301300",
              "url": "qerp.web.pd.spu.status",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 307000,
          "name": "B端商品",
          "code": "307000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 2,
          "children": [
            {
              "urResourceId": 307100,
              "name": "商品信息",
              "code": "307100",
              "url": "qerp.web.bpd.spu.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 307200,
              "name": "修改商品",
              "code": "307200",
              "url": "qerp.web.bpd.spu.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 307300,
              "name": "售卖开关",
              "code": "307300",
              "url": "qerp.web.pd.spu.status",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 307400,
              "name": "批量上新",
              "code": "307400",
              "url": "qerp.web.pd.spu.statusnew",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 307500,
              "name": "批量畅销",
              "code": "307500",
              "url": " qerp.web.pd.spu.statushot",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 308000,
          "name": "C端商品",
          "code": "308000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 3,
          "children": [
            {
              "urResourceId": 308100,
              "name": "商品信息",
              "code": "308100",
              "url": "qerp.web.cpd.spu.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 308200,
              "name": "修改商品",
              "code": "308200",
              "url": "qerp.web.cpd.spu.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 308300,
              "name": "售卖开关",
              "code": "308300",
              "url": "qerp.web.cpd.spu.status",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 308400,
              "name": "批量NEW",
              "code": "308400",
              "url": "qerp.web.cpd.spu.statusnew",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 308500,
              "name": "批量HOT",
              "code": "308500",
              "url": " qerp.web.cpd.spu.statushot",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 802000,
          "name": "online商品",
          "code": "802000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 4,
          "children": [
            {
              "urResourceId": 802100,
              "name": "商品信息",
              "code": "802100",
              "url": "qerp.web.ec.pd.spu.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 802200,
              "name": "修改商品",
              "code": "802200",
              "url": "qerp.web.ec.pd.spu.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 802300,
              "name": "导出数据",
              "code": "802300",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 802400,
              "name": "售卖开关",
              "code": "802400",
              "url": "qerp.web.pd.spu.status",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 802500,
              "name": "批量NEW",
              "code": "802500",
              "url": "qerp.web.pd.ospu.statusnew",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 802600,
              "name": "批量HOT",
              "code": "802600",
              "url": "qerp.web.pd.ospu.statushot",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 302000,
          "name": "分类管理",
          "code": "302000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 5,
          "children": [
            {
              "urResourceId": 302100,
              "name": "分类信息",
              "code": "302100",
              "url": "qerp.web.pd.category.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 302200,
              "name": "增改分类",
              "code": "302200",
              "url": "qerp.web.pd.category.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 311000,
          "name": "国家管理",
          "code": "311000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 6,
          "children": [
            {
              "urResourceId": 311100,
              "name": "国家信息",
              "code": "311100",
              "url": "qerp.web.pd.country.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 311200,
              "name": "增改国家",
              "code": "311200",
              "url": "qerp.web.pd.country.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 303000,
          "name": "品牌管理",
          "code": "303000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 7,
          "children": [
            {
              "urResourceId": 303100,
              "name": "品牌信息",
              "code": "303100",
              "url": "qerp.web.pd.brand.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 303200,
              "name": "增改品牌",
              "code": "303200",
              "url": "qerp.web.pd.brand.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 304000,
          "name": "规格管理",
          "code": "304000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 8,
          "children": [
            {
              "urResourceId": 304100,
              "name": "规格信息",
              "code": "304100",
              "url": "qerp.web.pd.type.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 304200,
              "name": "增改规格",
              "code": "304200",
              "url": "qerp.web.pd.type.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 314000,
          "name": "C端商品说明",
          "code": "314000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 9,
          "children": [
            {
              "urResourceId": 314100,
              "name": "说明信息",
              "code": "314100",
              "url": "qerp.web.pd.explain.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 314200,
              "name": "增改说明",
              "code": "314200",
              "url": "qerp.web.pd.brand.explaination.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 301700,
          "name": "商品库存",
          "code": "301700",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 10,
          "children": [
            {
              "urResourceId": 301710,
              "name": "online库存",
              "code": "301710",
              "url": "",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 301720,
                  "name": "库存修改",
                  "code": "301720",
                  "url": "qerp.web.pd.inv.online.change",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            },
            {
              "urResourceId": 301900,
              "name": "B端库存",
              "code": "301900",
              "url": "",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 301800,
                  "name": "库存修改",
                  "code": "301800",
                  "url": "qerp.web.pd.inv.change",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            }
          ]
        },
        {
          "urResourceId": 313000,
          "name": "保税仓库管理",
          "code": "313000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 11,
          "children": [
            {
              "urResourceId": 313100,
              "name": "仓库信息",
              "code": "313100",
              "url": "qerp.web.ws.warehouse.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 313200,
              "name": "增改仓库",
              "code": "313200",
              "url": "qerp.web.pd.taxWarehouse.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 305000,
          "name": "B端定时",
          "code": "305000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 12,
          "children": [
            {
              "urResourceId": 305100,
              "name": "增改定时",
              "code": "305100",
              "url": "qerp.web.pd.task.time.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 312000,
          "name": "C端定时",
          "code": "312000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 13,
          "children": [
            {
              "urResourceId": 312100,
              "name": "增改定时",
              "code": "312100",
              "url": "qerp.web.pd.task.time.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 309000,
          "name": "活动兑换商品",
          "code": "309000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 14,
          "children": [
            {
              "urResourceId": 309100,
              "name": "查看",
              "code": "309100",
              "url": "qerp.web.pd.spu.active.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 309200,
              "name": "增改商品",
              "code": "309200",
              "url": "qerp.web.pd.spu.active.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        }
      ]
    },
    {
      "urResourceId": 1200000,
      "name": "用户中心",
      "code": "1200000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 3,
      "children": [
        {
          "urResourceId": 1201000,
          "name": "C端用户管理",
          "code": "1201000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 1,
          "children": [
            {
              "urResourceId": 1201100,
              "name": "用户信息",
              "code": "1201100",
              "url": "qerp.web.c.user_consume_query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 803000,
          "name": "有赞用户管理",
          "code": "803000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 2,
          "children": [
            {
              "urResourceId": 803100,
              "name": "用户信息",
              "code": "803100",
              "url": "qerp.web.ec.user_consume_query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 803200,
              "name": "导出数据",
              "code": "803200",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 402500,
          "name": "pos用户管理",
          "code": "402500",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 3,
          "children": [
            {
              "urResourceId": 402510,
              "name": "会员信息",
              "code": "402510",
              "url": "qerp.web.qpos.mb.carda.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        }
      ]
    },
    {
      "urResourceId": 400000,
      "name": "运营中心",
      "code": "400000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 4,
      "children": [
        {
          "urResourceId": 404000,
          "name": "B端Banner",
          "code": "404000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 1,
          "children": [
            {
              "urResourceId": 404100,
              "name": "banner管理",
              "code": "404100",
              "url": "qerp.web.pd.banner.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 1002000,
          "name": "C端Banner",
          "code": "1002000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 2,
          "children": [
            {
              "urResourceId": 1002100,
              "name": "banner管理",
              "code": "1002100",
              "url": "qerp.web.pd.banner.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 1004000,
          "name": "B端推送",
          "code": "1004000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 4,
          "children": [
            {
              "urResourceId": 1004100,
              "name": "推送信息",
              "code": "1004100",
              "url": "qerp.web.pd.bpush.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 1004200,
              "name": "增改推送",
              "code": "1004200",
              "url": "qerp.web.pd.bPush.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 1004300,
              "name": "撤消推送",
              "code": "1004300",
              "url": "qerp.web.pd.bPush.revoke",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 1005000,
          "name": "C端推送",
          "code": "1005000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 5,
          "children": [
            {
              "urResourceId": 1005100,
              "name": "推送信息",
              "code": "1005100",
              "url": "qerp.web.pd.cpush.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 1005200,
              "name": "增改推送",
              "code": "1005200",
              "url": "qerp.web.pd.cpush.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 1005300,
              "name": "撤消推送",
              "code": "1005300",
              "url": "qerp.web.pd.cpush.revoke",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 409000,
          "name": "B端问答管理",
          "code": "409000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 6,
          "children": [
            {
              "urResourceId": 409099,
              "name": "问答信息",
              "code": "409099",
              "url": "qerp.web.pd.answer.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 409100,
              "name": "新增/修改问答",
              "code": "409100",
              "url": "qerp.web.pd.answer.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 401200,
          "name": "营销活动",
          "code": "401200",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 7,
          "children": [
            {
              "urResourceId": 401500,
              "name": "B端限时促销",
              "code": "401500",
              "url": "8",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 401501,
                  "name": "查看",
                  "code": "401501",
                  "url": "qerp.web.sp.activity.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 401502,
                  "name": "增改活动",
                  "code": "401502",
                  "url": "qerp.web.sp.activity.save",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 401503,
                  "name": "强制失效",
                  "code": "401503",
                  "url": "qerp.web.sp.activity.invalid",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            },
            {
              "urResourceId": 401600,
              "name": "B端活动进价",
              "code": "401600",
              "url": "9",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 401601,
                  "name": "查看",
                  "code": "401601",
                  "url": "qerp.web.sp.activity.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 401602,
                  "name": "增改活动",
                  "code": "401602",
                  "url": "qerp.web.sp.activity.save",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 401603,
                  "name": "强制失效",
                  "code": "401603",
                  "url": "qerp.web.sp.activity.invalid",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            },
            {
              "urResourceId": 401800,
              "name": "C端限时直降",
              "code": "401800",
              "url": "11",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 401801,
                  "name": "查看",
                  "code": "401801",
                  "url": "qerp.web.sp.activity.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 401802,
                  "name": "增改活动",
                  "code": "401802",
                  "url": "qerp.web.sp.activity.save",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 401803,
                  "name": "强制失效",
                  "code": "401803",
                  "url": "qerp.web.sp.activity.invalid",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            },
            {
              "urResourceId": 1003000,
              "name": "优惠券",
              "code": "1003000",
              "url": "",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": 3,
              "children": [
                {
                  "urResourceId": 401701,
                  "name": "券包管理",
                  "code": "401701",
                  "url": "qerp.web.pd.coupon.package.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 1003100,
                  "name": "优惠券信息",
                  "code": "1003100",
                  "url": "qerp.web.pd.coupon.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 1003200,
                  "name": "增改优惠券",
                  "code": "1003200",
                  "url": "qerp.web.pd.coupon.save",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 1003300,
                  "name": "注券",
                  "code": "1003300",
                  "url": "qerp.web.pd.coupon.create",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 1003400,
                  "name": "注券记录",
                  "code": "1003400",
                  "url": "qerp.web.pd.coupon.record",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 1003500,
                  "name": "熔断",
                  "code": "1003500",
                  "url": "qerp.web.pd.coupon.break",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            }
          ]
        },
        {
          "urResourceId": 401900,
          "name": "页面配置",
          "code": "401900",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 12,
          "children": [
            {
              "urResourceId": 401901,
              "name": "查看",
              "code": "401901",
              "url": "qerp.web.pd.configureId.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 401902,
              "name": "增改活动",
              "code": "401902",
              "url": "qerp.web.pd.configureId.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 402600,
          "name": "主题活动",
          "code": "402600",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 13,
          "children": [
            {
              "urResourceId": 402601,
              "name": "查看",
              "code": "402601",
              "url": "qerp.web.theme.activity.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 402602,
              "name": "增改活动",
              "code": "402602",
              "url": "qerp.web.theme.activity.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 402603,
              "name": "强制失效",
              "code": "402603",
              "url": "qerp.web.theme.activity.invalid",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        }
      ]
    },
    {
      "urResourceId": 900000,
      "name": "合作中心",
      "code": "900000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 5,
      "children": [
        {
          "urResourceId": 403000,
          "name": "门店管理",
          "code": "403000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 1,
          "children": [
            {
              "urResourceId": 403100,
              "name": "门店信息",
              "code": "403100",
              "url": "qerp.web.sp.shop.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 403200,
              "name": "增改门店",
              "code": "403200",
              "url": "qerp.web.sp.shop.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 403300,
              "name": "导出数据",
              "code": "403300",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 403400,
              "name": "门店详情",
              "code": "403400",
              "url": "qerp.web.sp.shop.info",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 405000,
          "name": "供应商管理",
          "code": "405000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 2,
          "children": [
            {
              "urResourceId": 405100,
              "name": "供应商信息",
              "code": "405100",
              "url": "qerp.web.pd.supplier.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 405200,
              "name": "增改供应商",
              "code": "405200",
              "url": "qerp.web.pd.supplier.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 901000,
          "name": "市场资源",
          "code": "901000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 3,
          "children": [
            {
              "urResourceId": 901100,
              "name": "资源信息",
              "code": "901100",
              "url": "qerp.web.pd.resource.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 901200,
              "name": "增改资源",
              "code": "901200",
              "url": "qerp.web.pd.resource.save",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        }
      ]
    },
    {
      "urResourceId": 1300000,
      "name": "财务中心",
      "code": "1300000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 6,
      "children": [
        {
          "urResourceId": 408100,
          "name": "提现管理",
          "code": "408100",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 1,
          "children": [
            {
              "urResourceId": 408000,
              "name": "提现管理",
              "code": "408000",
              "url": "qerp.web.sp.carry.cash.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 401000,
          "name": "掌柜充值",
          "code": "401000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 2,
          "children": [
            {
              "urResourceId": 401100,
              "name": "充值管理",
              "code": "401100",
              "url": "qerp.web.sp.voucher.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 402000,
          "name": "掌柜收支明细",
          "code": "402000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 3,
          "children": [
            {
              "urResourceId": 402100,
              "name": "收支信息",
              "code": "402100",
              "url": "qerp.web.sp.money.detail",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 402200,
              "name": "导出数据",
              "code": "402200",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 1301000,
          "name": "销售收支管理",
          "code": "1301000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 4,
          "children": [
            {
              "urResourceId": 1301100,
              "name": "收支信息",
              "code": "1301100",
              "url": "qerp.web.sp.income.pay",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 1301200,
              "name": "导出数据",
              "code": "1301200",
              "url": "qerp.web.sys.doc.task",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 1302000,
          "name": "分润管理",
          "code": "1302000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 5,
          "children": [
            {
              "urResourceId": 1302100,
              "name": "分润合计",
              "code": "1302100",
              "url": "",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 1302200,
                  "name": "分润信息",
                  "code": "1302200",
                  "url": "qerp.web.share.profitsum.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 1302300,
                  "name": "导出数据",
                  "code": "1302300",
                  "url": "qerp.web.sys.doc.task",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            },
            {
              "urResourceId": 1302400,
              "name": "直邮分润明细",
              "code": "1302400",
              "url": "",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 1302500,
                  "name": "分润信息",
                  "code": "1302500",
                  "url": "qerp.web.directDelivery.profit.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 1302600,
                  "name": "导出数据",
                  "code": "1302600",
                  "url": "qerp.web.sys.doc.task",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            },
            {
              "urResourceId": 1302700,
              "name": "保税分润明细",
              "code": "1302700",
              "url": "",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": [
                {
                  "urResourceId": 1302800,
                  "name": "分润信息",
                  "code": "1302800",
                  "url": "qerp.web.bondedws.profit.query",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                },
                {
                  "urResourceId": 1302900,
                  "name": "导出数据",
                  "code": "1302900",
                  "url": "qerp.web.sys.doc.task",
                  "remark": null,
                  "status": 1,
                  "statusStr": null,
                  "menu": 1,
                  "menuStr": null,
                  "rank": null,
                  "children": []
                }
              ]
            }
          ]
        },
        {
          "urResourceId": 407000,
          "name": "供应商收支",
          "code": "407000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 6,
          "children": [
            {
              "urResourceId": 407099,
              "name": "收支信息",
              "code": "407099",
              "url": "qerp.web.pd.settle.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 407100,
              "name": "导出数据",
              "code": "407100",
              "url": "qerp.web.pd.settle.export",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 407500,
              "name": "修改结算到期日",
              "code": "407500",
              "url": "qerp.web.pd.settle.update",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 407600,
              "name": "结算操作",
              "code": "407600",
              "url": "qerp.web.pd.settle.update1",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        }
      ]
    },
    {
      "urResourceId": 1100000,
      "name": "客服中心",
      "code": "1100000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 7,
      "children": [
        {
          "urResourceId": 406000,
          "name": "门店反馈",
          "code": "406000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 1,
          "children": [
            {
              "urResourceId": 406100,
              "name": "反馈信息",
              "code": "406100",
              "url": "qerp.web.sp.feedback.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 1102000,
          "name": "用户反馈",
          "code": "1102000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 2,
          "children": [
            {
              "urResourceId": 1102100,
              "name": "用户反馈",
              "code": "1102100",
              "url": "qerp.web.pd.feedback.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 1104000,
          "name": "C端客服工单",
          "code": "1104000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 3,
          "children": [
            {
              "urResourceId": 1103200,
              "name": "工单信息",
              "code": "1103200",
              "url": "qerp.web.ws.bin.udeskticket",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 1103000,
          "name": "客服工单",
          "code": "1103000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 4,
          "children": [
            {
              "urResourceId": 1103100,
              "name": "工单信息",
              "code": "1103100",
              "url": "qerp.web.pd.customservice.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        }
      ]
    },
    {
      "urResourceId": 700000,
      "name": "数据中心",
      "code": "700000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 8,
      "children": [
        {
          "urResourceId": 708000,
          "name": "APP数据",
          "code": "708000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 1,
          "children": [
            {
              "urResourceId": 708100,
              "name": "APP数据",
              "code": "708100",
              "url": "qerp.web.rp.qtoolsApp.data",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 703000,
          "name": "商品数据",
          "code": "703000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 2,
          "children": [
            {
              "urResourceId": 703100,
              "name": "商品分析",
              "code": "703100",
              "url": "qerp.web.rp.pd.analysis.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 703200,
              "name": "分类分析",
              "code": "703200",
              "url": "qerp.web.rp.category.analysis.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 703300,
              "name": "商品数据",
              "code": "703300",
              "url": "qerp.web.rp.spu.data.page",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 704000,
          "name": "订单数据",
          "code": "704000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 3,
          "children": [
            {
              "urResourceId": 704100,
              "name": "门店订单",
              "code": "704100",
              "url": "qerp.web.rp.shop.order.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 704200,
              "name": "POS订单",
              "code": "704200",
              "url": "qerp.web.rp.pos.order.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 701000,
          "name": "采购数据",
          "code": "701000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 4,
          "children": [
            {
              "urResourceId": 701100,
              "name": "采购数据",
              "code": "701100",
              "url": "qerp.web.rp.proposal.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 702000,
          "name": "门店数据",
          "code": "702000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 5,
          "children": [
            {
              "urResourceId": 702100,
              "name": "销售数据",
              "code": "702100",
              "url": "qerp.web.rp.shop.sale.data.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 702200,
              "name": "门店库存",
              "code": "702200",
              "url": "qerp.web.qpos.pd.inv.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 702300,
              "name": "历史库存",
              "code": "702300",
              "url": "qerp.web.qpos.pd.historyInv.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 702400,
              "name": "联营分成",
              "code": "702400",
              "url": "qerp.web.rp.shop.Joint.division.page",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 705000,
          "name": "仓库数据",
          "code": "705000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 6,
          "children": [
            {
              "urResourceId": 705100,
              "name": "实时库存",
              "code": "705100",
              "url": "qerp.web.pd.invdata.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 705200,
              "name": "历史库存",
              "code": "705200",
              "url": "qerp.web.pd.historyInvdata.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 705300,
              "name": "商品效期",
              "code": "705300",
              "url": "qerp.web.pd.validDate.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 706000,
          "name": "财务数据",
          "code": "706000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 7,
          "children": [
            {
              "urResourceId": 706100,
              "name": "门店成本",
              "code": "706100",
              "url": "qerp.web.sp.shopCost.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 706200,
              "name": "成本核算",
              "code": "706200",
              "url": "qerp.web.pd.costmonthdata.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 706300,
              "name": "采购到货",
              "code": "706300",
              "url": "qerp.web.ws.purchasedata.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            },
            {
              "urResourceId": 706400,
              "name": "门店发票",
              "code": "706400",
              "url": "qerp.web.sp.shopdata.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        },
        {
          "urResourceId": 707000,
          "name": "门店POS",
          "code": "707000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 8,
          "children": [
            {
              "urResourceId": 707100,
              "name": "门店POS",
              "code": "707100",
              "url": "qerp.web.sp.shop.list",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        }
      ]
    },
    {
      "urResourceId": 600000,
      "name": "账号中心",
      "code": "600000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 9,
      "children": [
        {
          "urResourceId": 601000,
          "name": "Q本营权限",
          "code": "601000",
          "url": "",
          "remark": null,
          "status": 1,
          "statusStr": null,
          "menu": 1,
          "menuStr": null,
          "rank": 9,
          "children": [
            {
              "urResourceId": 601100,
              "name": "Q本营权限",
              "code": "601100",
              "url": "qerp.web.ur.user.query",
              "remark": null,
              "status": 1,
              "statusStr": null,
              "menu": 1,
              "menuStr": null,
              "rank": null,
              "children": []
            }
          ]
        }
      ]
    },
    {
      "urResourceId": 100000,
      "name": "C端配置中心",
      "code": "200000",
      "url": "",
      "remark": null,
      "status": 1,
      "statusStr": null,
      "menu": 1,
      "menuStr": null,
      "rank": 1,
      "children": [{
        "urResourceId": 110000,
        "name": "提单页提示",
        "code": "110000",
        "url": "",
        "remark": null,
        "status": 1,
        "statusStr": null,
        "menu": 1,
        "menuStr": null,
        "rank": 1,
      }]
    }
  ]
  export default SiderBarData;
